### ISSUE TITLE
Make it more compact

### ISSUE THREAD

**Issue by bfred-it** [tanmayrajani/notifications-preview-github#15]
As a default or as an option

<img width="520" alt="screen shot 2017-08-28 at 14 18 25" src="https://user-images.githubusercontent.com/1402241/29763123-fbe26262-8bfb-11e7-957b-0cc35d7f5a9e.png">

This is the additional style I use:

```css
#NPG-dropdown {
	width: auto;
	padding: 5px;
}
#NPG-dropdown .boxed-group {
	margin-bottom: 6px;
}
#NPG-dropdown .boxed-group h3 {
	padding-right: 45px; /* Avoids wrap with long repo names */
}
#NPG-dropdown .list-group-item-name {
	padding-right: 15px;
}
#NPG-dropdown .age,
#NPG-dropdown .avatar-stack {
	display: none;
}
```
