### ISSUE TITLE
Preview notification count

### ISSUE THREAD

**Issue by bfred-it** [tanmayrajani/notifications-preview-github#19]
Depends on #17 

<img width="32" alt="notification count preview" src="https://user-images.githubusercontent.com/1402241/29816367-0bf7691c-8cde-11e7-8611-8b135e57a3cb.png">

CSS used in the screenshot (+ the number in the dom)

```css
.unread {
    top: -5px;
    left: 11px;
    font-size: 13px;
    line-height: 0.8;
    color: transparent;
    font-weight: bold;
    -webkit-background-clip: text;
    border: none;
    border-radius: 0;
}
```
